site_name: Matech MkDocs Template
#site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md
# standard defacto theme - https://github.com/squidfunk/mkdocs-material
theme:
  name: material